### ISSUE TITLE
Quinoa TPL Can Only Be Built as Part of Quinoa

### ISSUE THREAD

**Issue by rspavel** [quinoacomputing/quinoa-tpl#1] opened 2017-03-24 18:11 UTC
Due to dependences on files in https://github.com/quinoacomputing/quinoa/tree/master/cmake and a hardcoded relative path at https://github.com/quinoacomputing/quinoa-tpl/blob/master/CMakeLists.txt#L17 the quinoa-tpl libraries can only be built if they are in a subdirectory of quinoa or quinoa-ng. 

If this is intended behavior feel free to delete this, but it makes setting up a development environment with pre-built TPLs noticeably more difficult.

**Comment by jbakosi** [comment] 2017-03-24 18:35
This is a consequence of separating the TPL and code repos. I knew this was going to happen and I am planning to look at it. I will attempt to separate the two without too much duplication across the two repos of the cmake directory that has been shared. In the meantime, suggestions are welcome on how best to do this.

In the meantime, I am using it by creating a symlink for `../cmake` as currently required by `TPL/CMakeLists.txt`.

**Comment by jbakosi** [comment] 2017-03-24 20:16
So the problem is that most of the cmake code under the `/cmake` directory is required by both the quinoa as well as the quinoa-tpl build. Does anyone have a reasonable suggestion how to share this code between the two repos without having to duplicate it?

1. One idea is to just copy the directory to both repos but then changes to each should be followed by changes to the other and that will definitely diverge and will be a source of errors.

2. Another one is to include it via a submodule. However, this submodule now must be _required_ in both repos, i.e., using each without `--recursive` will not produce a working repo. @quinoacomputing/dev, do you have experience with something like this?

Any other reasonable solutions? I don't like either of the above.

**Comment by jbakosi** [comment] 2017-03-24 20:19
Option 2 would work if there was a way to require the clone of the new cmake submodule when cloning either of quinoa or quinoa-tpl repos. Is this possible? However, even if it can be made required to be recursive, that would still require a developer to now deal with submodule-crap if one wants to make changes in the cmake directory. Still more complicated than I would like it.

**Comment by jbakosi** [comment] 2017-04-19 22:20
TPLs are used with submodules and cmake is merged in via git subtree.

**Closed as completed by jbakosi** 2017-04-19 22:20 UTC
Labels: bug, help wanted
